### PR TITLE
Libsass 3.2.5 stable branch - source maps, precision

### PR DESCRIPTION
**Pull request by absalomedia**
This is a better edition of the initial pull request I did for providing source map controls & precision into the Apache / Zend implementation of Libsass.

### CODE REVIEW

**Comment by kevinliteon** [comment]
it looks great! what that prevents the pull request?

**Comment by absalomedia** [comment]
I do believe I'm waiting on @chrinor2002 to merge it correctly. My master branch is now working on tests with Travis, Coveralls & maybe building a Windows edition of it. That's why I forked a separate 'stable' branch

**Comment by chrinor2002** [comment]
I think @pilif is actually the original owner for this repo.  My c and c++ skills are minimal at best.

**Comment by pilif** [comment]
looks very good. Thank you. Do you want to rebase it on top of current master so it can be merged, or should I resolve the conflicts for you? Both is fine by me.

Sorry for the somewhat late response. I was kinda busy.

**Comment by pilif** [comment]
thank you. I have manually merged your changes.

**Comment by absalomedia** [comment]
@pilif you might want to fix the documentation & build name as the merge looks to still have my fork details in it.

**Pull request merged**
